# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used.


PyTorch a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a $5\times 3$ matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Construct a randomly initialized matrix

In [2]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3432, 0.2033, 0.7338],
        [0.2978, 0.6774, 0.4269],
        [0.2794, 0.2740, 0.4634],
        [0.4133, 0.6200, 0.4484],
        [0.7276, 0.4080, 0.0733]])


Get its size

In [3]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [4]:
x[1:3] = 2
print(x)

tensor([[0.3432, 0.2033, 0.7338],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.4133, 0.6200, 0.4484],
        [0.7276, 0.4080, 0.0733]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [12]:
x1 = torch.FloatTensor(2, 17)
x2 =torch.FloatTensor(3, 1)
x3 =torch.LongTensor(5,2,1)
x3[:]=7
x4 = torch.ByteTensor(5)
x4[1:4]=1
print(x4)

tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [13]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.5041, 0.2579, 0.9639],
        [2.3230, 2.9428, 2.6039],
        [2.9322, 2.9042, 2.3029],
        [1.3906, 1.0988, 1.4328],
        [1.2314, 1.3230, 0.0988]])


### 2.2 Addition: syntax 2

In [14]:
print(torch.add(x, y))

tensor([[0.5041, 0.2579, 0.9639],
        [2.3230, 2.9428, 2.6039],
        [2.9322, 2.9042, 2.3029],
        [1.3906, 1.0988, 1.4328],
        [1.2314, 1.3230, 0.0988]])


### 2.3 Addition: giving an output tensor

In [15]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.5041, 0.2579, 0.9639],
        [2.3230, 2.9428, 2.6039],
        [2.9322, 2.9042, 2.3029],
        [1.3906, 1.0988, 1.4328],
        [1.2314, 1.3230, 0.0988]])


### 2.4 Addition: in-place

adds `x` to `y`

In [16]:
y.add_(x)
print(y)

tensor([[0.5041, 0.2579, 0.9639],
        [2.3230, 2.9428, 2.6039],
        [2.9322, 2.9042, 2.3029],
        [1.3906, 1.0988, 1.4328],
        [1.2314, 1.3230, 0.0988]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [17]:
print(x[:, 1])

tensor([0.2033, 2.0000, 2.0000, 0.6200, 0.4080])


**Read later**: 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [23]:

a = torch.Tensor(2,4)
b = torch.rand(4,2)

print(torch.mul(a, b))

print(torch.div(a, b))

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [24]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [25]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [26]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [27]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a NumPy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [30]:
hi = torch.Tensor(5,2)
ni = hi.numpy()
back = torch.from_numpy(ni)
print(back)

tensor([[-3.2898e+31,  4.4497e-41],
        [ 6.7310e-31,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])


## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [31]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
